name: Godot export action
descripton: Exports a Godot project

inputs:
  debug:
    type: boolean
    default: false
  path:
    type: string
    required: true
  target:
    type: string
    required: true

runs:
  using: composite
  steps:
  - run: mkdir -v -p $(dirname "${{ inputs.path }}")
    shell: bash
  - id: get-godot-version
    run: echo "godot-version=$(godot --version)" >> $GITHUB_OUTPUT
    shell: bash
  - if: ${{ startsWith(steps.get-godot-version.outputs.godot-version, '4') }}
    run: godot -v --headless ${{ inputs.debug && '--export-debug' || '--export-release' }} "${{ inputs.target }}" "${{ inputs.path }}"
    shell: bash
  - if: ${{ startsWith(steps.get-godot-version.outputs.godot-version, '3') }}
    run: godot -v ${{ inputs.debug && '--export-debug' || '--export' }} "${{ inputs.target }}" "${{ inputs.path }}"
    shell: bash
