name: Godot export action
descripton: Exports a Godot project

inputs:
  debug:
    type: boolean
    default: false
  path:
    type: string
    required: true
  target:
    type: string
    required: true

runs:
  using: composite
  steps:
  - run: mkdir -v -p $(dirname "${{ inputs.path }}")
    shell: bash
  - run: godot -v ${{ inputs.debug && '--export-debug' || '--export' }} "${{ inputs.target }}" "${{ inputs.path }}"
    shell: bash
