name: Godot export action
descripton: Exports a Godot project

inputs:
  path:
    type: string
    required: true
  target:
    type: string
    required: true

runs:
  using: composite
  steps:
  - run: mkdir -v -p $(dirname "${{ inputs.path }}")
    shell: bash
  - run: godot -v --export "${{ inputs.target }}" "${{ inputs.path }}"
    shell: bash
